name: Wellness Tourism MLOps Pipeline


# Trigger pipeline automatically whenever code is pushed to main branch
on:
  push:
    branches:
      - main



jobs:


# ==================================================
# 1. DATA VALIDATION + DATA REGISTRATION
# ==================================================

  validate-register-dataset:

    runs-on: ubuntu-latest

    steps:

      # Download GitHub repository code
      - name: Checkout Repository
        uses: actions/checkout@v4


      # Install ML pipeline dependencies
      - name: Install Dependencies
        run: |
          pip install -r wellness-tourism-mlops/requirements.txt


      # Validate dataset columns and summary
      - name: Validate Dataset
        run: |
          python wellness-tourism-mlops/data_pipeline/validate_dataset.py


      # Upload raw dataset to Hugging Face Dataset Repository
      - name: Register Dataset to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}

        run: |
          python wellness-tourism-mlops/data_pipeline/upload_dataset.py




# ==================================================
# 2. DATA PREPARATION
# ==================================================

  prepare-data:

    needs: validate-register-dataset

    runs-on: ubuntu-latest


    steps:


      - name: Checkout Repository
        uses: actions/checkout@v4



      - name: Install Dependencies
        run: |
          pip install -r wellness-tourism-mlops/requirements.txt



      # Cleaning + splitting + uploading train/test data
      - name: Prepare Dataset
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}

        run: |
          python wellness-tourism-mlops/data_pipeline/prepare_dataset.py





# ==================================================
# 3. MODEL TRAINING + EXPERIMENT TRACKING
# ==================================================

  train-model:

    needs: prepare-data

    runs-on: ubuntu-latest


    steps:


      - name: Checkout Repository
        uses: actions/checkout@v4



      - name: Install Dependencies
        run: |
          pip install -r wellness-tourism-mlops/requirements.txt



      # Train model, tune parameters,
      # evaluate performance and upload model
      - name: Train Machine Learning Model
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}

        run: |
          python wellness-tourism-mlops/data_pipeline/train_model.py





# ==================================================
# 4. DEPLOY STREAMLIT APPLICATION
# ==================================================

  deploy-app:

    needs:
      - train-model

    runs-on: ubuntu-latest



    steps:


      - name: Checkout Repository
        uses: actions/checkout@v4



      - name: Install Dependencies
        run: |
          pip install -r wellness-tourism-mlops/requirements.txt



      # Upload prediction_app files to Hugging Face Space
      - name: Deploy Streamlit App to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}

        run: |
          python wellness-tourism-mlops/deployment/deploy_prediction_app.py
